version: '3.8'

services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: my-frontend-container-v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - frontend_network


networks:
  frontend_network:
    driver: bridge
