version: '3.8'

services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: happie-frontend-v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - frontend_network

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: happie-backend-v1
    ports:
      - "8085:8085"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
